import "../assets/sass/lesson.sass";
import katex from "katex";
import "katex/dist/katex.min.css";
import { initLessonChrome, renderLessonHeader, renderLessonFooter, setFeedback } from "./shared";

const M=tex=>`<span class="laws-math">${katex.renderToString(String.raw`\displaystyle `+tex,{throwOnError:true,strict:"ignore"})}</span>`;
const $=id=>document.getElementById(id);
const fmt=(n,digits=3)=>Number(n.toFixed(digits)).toString().replaceAll('-','−');
const intro=(n,topic,title,text)=>`<div class="lesson-section__intro" data-reveal><p class="lesson-kicker"><span>${n}</span> ${topic}</p><h2>${title}</h2><p>${text}</p></div>`;
const range=(id,title,min,max,step,value)=>`<label for="${id}">${title}<output id="${id}-value"></output></label><input type="range" id="${id}" min="${min}" max="${max}" step="${step}" value="${value}">`;
const button=(id,text)=>`<button type="button" class="laws-button" id="${id}">${text}</button>`;
const gcd=(a,b)=>{a=Math.abs(a);b=Math.abs(b);while(b){const remainder=a%b;a=b;b=remainder;}return a||1;};
function rational(n,d){if(d<0){n=-n;d=-d;}const g=gcd(n,d);return[n/g,d/g];}
function fraction(n,d){[n,d]=rational(n,d);return d===1?String(n):String.raw`\frac{${n}}{${d}}`;}
function piFraction(n,d){[n,d]=rational(n,d);if(n===0)return'0';const sign=n<0?'-':'';n=Math.abs(n);return d===1?`${sign}${n===1?'':n}\\pi`:`${sign}\\frac{${n===1?'':n}\\pi}{${d}}`;}
function degreePi(degrees){const [n,d]=rational(Math.round(degrees*1000000),180000000);return piFraction(n,d);}
const normalized=degrees=>{const value=((degrees%360)+360)%360;return Math.abs(value)<1e-8||Math.abs(value-360)<1e-8?0:value;};
function position(degrees){const a=normalized(degrees);if(Math.abs(a%90)<1e-8)return['Positive x-axis','Positive y-axis','Negative x-axis','Negative y-axis'][Math.round(a/90)%4];return`Quadrant ${['I','II','III','IV'][Math.floor(a/90)]}`;}
const standard=[30,45,60,90,180,270,360];
const checks=[
 ['Positive direction',String.raw`\theta>0\ \text{means rotation is…}`,[String.raw`\text{Clockwise}`,String.raw`\text{Counterclockwise}`],1,'Positive rotations are counterclockwise; negative rotations are clockwise.'],
 ['Standard position',String.raw`\text{The initial side lies on…}`,[String.raw`\text{The positive x-axis}`,String.raw`\text{The positive y-axis}`,String.raw`\text{Any ray through the origin}`],0,'Standard position puts the vertex at the origin and the initial side on the positive x-axis.'],
 ['Terminal position',String.raw`-90^\circ`,[String.raw`\text{Quadrant IV}`,String.raw`\text{Negative y-axis}`,String.raw`\text{Positive y-axis}`],1,'The terminal side is on the negative y-axis, so the angle is quadrantal and belongs to no quadrant.'],
 ['One radian',String.raw`\theta=1\ \text{radian when…}`,[String.raw`s=1`,String.raw`s=r`,String.raw`s=2\pi r`],1,'A radian is the ratio s/r. One radian means the intercepted arc is as long as the radius.'],
 ['Full turn',String.raw`360^\circ`,[String.raw`\pi`,String.raw`2\pi`,String.raw`180\pi`],1,'The circumference is 2πr, so a full turn has (2πr)/r = 2π radians.'],
 ['Degree conversion',String.raw`800^\circ`,[String.raw`\frac{40\pi}{9}`,String.raw`\frac{80\pi}{9}`,String.raw`\frac{9\pi}{40}`],0,'Multiply 800 by π/180 and reduce: 800π/180 = 40π/9.'],
 ['Radian conversion',String.raw`\frac{13\pi}{12}`,[String.raw`195^\circ`,String.raw`156^\circ`,String.raw`13^\circ`],0,'Multiply by 180/π. The π cancels, giving 13 × 15 = 195 degrees.'],
 ['Coterminal with 7π/4',String.raw`\text{Choose a negative coterminal angle.}`,[String.raw`-\frac{\pi}{4}`,String.raw`-\frac{7\pi}{4}`,String.raw`-\frac{3\pi}{4}`],0,'Subtract 2π: 7π/4 − 8π/4 = −π/4.'],
 ['Reduce a multi-turn angle',String.raw`\frac{10\pi}{3}`, [String.raw`\frac{4\pi}{3}`,String.raw`\frac{\pi}{3}`,String.raw`\frac{2\pi}{3}`],0,'Subtract 2π = 6π/3 to get 4π/3, whose terminal side lies in Quadrant III.'],
 ['Same terminal side?',String.raw`270^\circ\ \text{and}\ -90^\circ`,[String.raw`\text{Yes}`,String.raw`\text{No}`],0,'They differ by 360 degrees, exactly one full turn.'],
 ['Minute-hand travel',String.raw`\text{One minute: angular distance}`, [String.raw`\frac{\pi}{30}\ \text{rad}`,String.raw`\frac{\pi}{60}\ \text{rad}`,String.raw`2\pi\ \text{rad}`],0,'The minute hand makes a full turn in 60 minutes: 2π/60 = π/30 radians, or 6 degrees.'],
 ['Coterminal test',String.raw`\alpha\ \text{and}\ \beta\ \text{are coterminal when…}`, [String.raw`\alpha-\beta=180^\circ`,String.raw`\alpha-\beta=360^\circ k,\ k\in\mathbb Z`,String.raw`\alpha+\beta=360^\circ`],1,'Coterminal angles differ by an integer number of complete turns.'],
];

document.querySelector('#app').innerHTML=`${renderLessonHeader('6.1')}<main class="laws-lesson angles-lesson">
<section class="lesson-hero lesson-hero--angles"><div class="lesson-hero__copy" data-reveal><p class="lesson-kicker"><span>Section 6.1</span> Angle measure</p><h1>Follow the turn.<br><em>Measure the arc.</em></h1><p class="lesson-hero__lede">An angle records a rotation—not just the space between two rays. See how direction, full turns, degrees, and radians describe the same motion.</p><div class="lesson-hero__actions"><a class="lesson-button lesson-button--dark" href="#rotations">Turn the ray</a><span>About 30 minutes · interactive</span></div></div><div class="angle-hero-art" data-reveal><p class="tool-label">One radian: arc length equals radius</p><svg id="angle-hero-chart" viewBox="50 50 400 400" role="img" aria-label="A central angle of one radian with an intercepted arc equal to the radius"></svg><div class="laws-equation">${M(String.raw`\theta=\frac{s}{r}\quad\text{and}\quad s=r\ \Rightarrow\ \theta=1`)}</div></div></section>
<section class="lesson-objectives" aria-label="Lesson objectives" data-reveal><p>By the end, you can</p><ol><li><span>01</span><p>Read signed angles in standard position</p></li><li><span>02</span><p>Explain a radian as an arc-to-radius ratio</p></li><li><span>03</span><p>Convert exactly between degrees and radians</p></li><li><span>04</span><p>Find positive and negative coterminal angles</p></li></ol></section>
<section class="lesson-section" id="rotations">${intro('01','Understand the rotation','Same starting ray.<br>Many possible turns.',`In <strong>standard position</strong>, the vertex is the origin and the initial side is the positive x-axis. Counterclockwise rotation is positive; clockwise rotation is negative. One complete turn is ${M('360^\\circ')}.`)}<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Rotating-ray studio</p>${range('turn-angle','Signed angle (degrees)',-720,1080,1,225)}<div class="angle-presets">${[-450,-90,0,45,90,180,225,360,720].map(d=>`<button type="button" class="angle-preset" data-turn="${d}">${M(`${d}^\\circ`)}</button>`).join('')}</div>${button('turn-play','Animate a turn')}<div class="laws-note" id="turn-reading" aria-live="polite"></div></div><div class="angle-plot"><svg id="turn-chart" viewBox="0 0 500 500" role="img" aria-label="An angle in standard position with its initial and terminal rays"></svg><p>Gold: initial side · coral: terminal side · violet rings: complete turns. An axis is a boundary between quadrants.</p></div></div><div class="angle-types">${[['Acute','0^\\circ<\\theta<90^\\circ'],['Right','\\theta=90^\\circ'],['Obtuse','90^\\circ<\\theta<180^\\circ'],['Straight','\\theta=180^\\circ']].map(([name,tex])=>`<article><strong>${name}</strong><p>${M(tex)}</p></article>`).join('')}</div><aside class="laws-note">A <strong>quadrantal angle</strong> has its terminal side on an axis. Angles can also exceed one full turn or be negative; their terminal position alone does not record the whole rotation.</aside></section>
<section class="lesson-section lesson-section--soft" id="radians">${intro('02','Build a radian','Compare two lengths.<br>The radius cancels.',`For a central angle, radian measure is ${M(String.raw`\theta=s/r`)}. If the intercepted arc has length ${M('r')}, the angle is one radian. Changing the circle's radius changes both lengths together, leaving their ratio unchanged.`)}<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Arc and radius laboratory</p>${range('radian-radius','Radius r',0.5,4,0.5,2)}${range('radian-theta','Central angle (radians)',0,Math.PI*2,'any',1)}<div class="angle-presets">${[[1,'1'],[Math.PI/2,String.raw`\pi/2`],[Math.PI,String.raw`\pi`],[Math.PI*2,String.raw`2\pi`]].map(([value,tex])=>`<button type="button" class="angle-preset" data-radian="${value}">${M(tex)}</button>`).join('')}</div><div id="radian-reading" class="laws-note" aria-live="polite"></div></div><div class="angle-plot"><svg id="radian-chart" viewBox="0 0 500 500" role="img" aria-label="Circle showing a radius and the intercepted arc of a central angle"></svg><div class="angle-length-bars" id="radian-bars"></div></div></div><div class="laws-card-grid"><article class="laws-card"><p class="tool-label">A whole circumference</p><div class="laws-equation">${M(String.raw`\frac{2\pi r}{r}=2\pi`)}</div><p>One turn is ${M(String.raw`360^\circ=2\pi\ \text{rad}`)}; half a turn is ${M(String.raw`180^\circ=\pi\ \text{rad}`)}.</p></article><article class="laws-card"><p class="tool-label">One radian in degrees</p><div class="laws-equation">${M(String.raw`1\ \text{rad}=\frac{180^\circ}{\pi}\approx57.296^\circ`)}</div><p>The number 1 without a degree symbol usually means one radian in trigonometric angle expressions.</p></article></div></section>
<section class="lesson-section" id="convert">${intro('03','Convert exactly','Use a full turn<br>as your conversion bridge.',`Multiply degrees by ${M(String.raw`\pi/180`)} to get radians. Multiply radians by ${M(String.raw`180/\pi`)} to get degrees. The conversion factors come from ${M(String.raw`180^\circ=\pi\ \text{rad}`)}.`)}<div class="angle-common" aria-label="Common degree and radian pairs">${standard.map(d=>`<button type="button" class="angle-common-card" data-common="${d}">${M(`${d}^\\circ`)}<span>↕</span>${M(degreePi(d))}</button>`).join('')}</div><div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Exact conversion workbench</p><label for="convert-mode">Direction</label><select id="convert-mode"><option value="degrees">Degrees → radians</option><option value="pi">A multiple of π → degrees</option></select><div id="convert-degree-controls"><label for="convert-degrees">Angle in degrees</label><input type="number" id="convert-degrees" value="800" step="any"></div><div id="convert-pi-controls" hidden><p>Enter the coefficient ${M(String.raw`(n/d)\pi`)}.</p><label for="convert-n">Numerator n</label><input type="number" id="convert-n" value="13" step="1"><label for="convert-d">Denominator d</label><input type="number" id="convert-d" value="12" step="1"></div><div class="angle-presets">${button('convert-example-deg','Try 800°')}${button('convert-example-pi',`Try ${M(String.raw`13\pi/12`)}`)}</div></div><div class="laws-result" id="convert-reading" aria-live="polite"></div></div></section>
<section class="lesson-section lesson-section--soft" id="coterminal">${intro('04','Same terminal side','Add a full turn.<br>Keep the terminal side.',`Coterminal angles share a terminal side. Their measures differ by ${M(String.raw`360^\circ k`)} or ${M(String.raw`2\pi k`)}, where ${M(String.raw`k\in\mathbb Z`)}. Their paths can have different directions or different numbers of turns.`)}<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Coterminal-angle builder</p><label for="co-base">Starting angle in degrees</label><input type="number" id="co-base" value="315" step="any"><div class="angle-presets">${[[315,String.raw`7\pi/4`],[600,String.raw`10\pi/3`],[270,String.raw`270^\circ`]].map(([value,tex])=>`<button type="button" class="angle-preset" data-co="${value}">${M(tex)}</button>`).join('')}</div>${range('co-k','Whole turns k',-4,4,1,0)}<div class="laws-note" id="co-reading" aria-live="polite"></div><label for="co-test">Test another angle in degrees</label><input type="number" id="co-test" step="any" value="-45"><p class="answer-feedback" id="co-feedback" aria-live="polite"></p></div><div class="angle-plot"><svg id="co-chart" viewBox="0 0 500 500" role="img" aria-label="Coterminal rays occupy the same terminal position"></svg><div class="angle-co-examples" id="co-examples" aria-live="polite"></div></div></div><aside class="laws-note">Reduce to one positive turn using ${M(String.raw`0\le\theta<360^\circ`)} or ${M(String.raw`0\le\theta<2\pi`)}. A full turn reduces to zero, not to an angle in Quadrant IV.</aside></section>
<section class="lesson-section" id="clock">${intro('05','Motion in context','One minute.<br>A small clockwise turn.',`A minute hand completes ${M(String.raw`360^\circ=2\pi\ \text{rad}`)} in 60 minutes. Its <strong>angular distance</strong> is positive; its <strong>signed rotation</strong> is negative because it turns clockwise.`)}<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Minute-hand explorer</p>${range('clock-minutes','Elapsed minutes',0,120,1,1)}<div class="laws-note" id="clock-reading" aria-live="polite"></div><p>Start at 12. The hour hand is omitted so the minute-hand motion is easy to track.</p></div><div class="angle-plot"><svg id="clock-chart" viewBox="0 0 500 500" role="img" aria-label="Clock with a minute hand showing clockwise angular travel"></svg></div></div></section>
<section class="lesson-section lesson-section--ink" id="readiness">${intro('06','Practice','Read the turn.<br>Keep the units.',"Use exact multiples of π whenever possible. Separate the amount of rotation from the terminal position.")}<p class="laws-score" id="angle-score" aria-live="polite">0 of ${checks.length} checks solved</p><div class="laws-check-grid">${checks.map((q,i)=>`<article class="laws-check"><p class="tool-label">${q[0]}</p><h3>${M(q[1])}</h3><fieldset class="laws-choices"><legend>Your answer</legend>${q[2].map((tex,j)=>`<label><input type="radio" name="angle-practice-${i}" value="${j}"><span>${M(tex)}</span></label>`).join('')}</fieldset><button type="button" class="laws-button" data-angle-check="${i}">Check answer</button><p class="answer-feedback" id="angle-feedback-${i}" aria-live="polite"></p></article>`).join('')}</div></section>
</main>${renderLessonFooter({previous:{href:'pages/sections/4-5.html',label:'Section 4.5 · Exponential and logarithmic equations'},next:{href:'pages/sections/6-2.html',label:'Section 6.2 · Right-triangle trigonometry'}})}`;

// Every circular diagram has a square viewBox and one physical radius for both axes.
const point=(r,degrees,cx=250,cy=250)=>[cx+r*Math.cos(degrees*Math.PI/180),cy-r*Math.sin(degrees*Math.PI/180)];
function arc(r,start,sweep){let d='';const n=Math.max(2,Math.ceil(Math.abs(sweep)/2));for(let i=0;i<=n;i++){const [x,y]=point(r,start+sweep*i/n);d+=`${i?'L':'M'}${x.toFixed(3)},${y.toFixed(3)} `;}return d;}
function ray(r,degrees,color,width=5){const [x,y]=point(r,degrees);return`<line x1="250" y1="250" x2="${x}" y2="${y}" stroke="${color}" stroke-width="${width}" stroke-linecap="round"/><circle cx="${x}" cy="${y}" r="5" fill="${color}"/>`;}
function circleScene(svg,degrees,{axes=true,start=0,clock=false}={}){const turns=Math.floor(Math.abs(degrees)/360),remainder=degrees%360,end=start+degrees;let art=`<circle cx="250" cy="250" r="180" fill="none" stroke="var(--line)" stroke-width="2"/>`;if(axes)art+=`<path class="angle-axis" d="M30 250H470M250 30V470"/><text class="angle-label" x="470" y="275">x</text><text class="angle-label" x="266" y="35">y</text><text class="angle-quadrant" x="360" y="130">I</text><text class="angle-quadrant" x="130" y="130">II</text><text class="angle-quadrant" x="130" y="390">III</text><text class="angle-quadrant" x="360" y="390">IV</text>`;if(clock)art+=Array.from({length:12},(_,i)=>{const [x,y]=point(205,90-i*30);return`<text class="angle-clock-label" x="${x}" y="${y+6}" text-anchor="middle">${i===0?12:i}</text>`;}).join('');for(let i=0;i<Math.min(turns,4);i++)art+=`<circle cx="250" cy="250" r="${105+i*12}" fill="none" stroke="var(--violet)" stroke-width="3"/>`;if(Math.abs(remainder)>1e-8)art+=`<path d="${arc(85,start,remainder)}" fill="none" stroke="var(--violet)" stroke-width="5"/>`;art+=ray(180,start,'var(--gold)',7)+ray(180,end,'var(--coral)',4)+`<circle cx="250" cy="250" r="7" fill="var(--ink)"/>`;if(degrees!==0){const direction=degrees>0?1:-1,tipAngle=start+(remainder||direction*350),[tx,ty]=point(85,tipAngle);art+=`<path d="M0 0 L-12 -6 L-12 6 Z" fill="var(--violet)" transform="translate(${tx} ${ty}) rotate(${-tipAngle-direction*90})"/>`;}svg.innerHTML=art;svg.setAttribute('aria-label',clock?`Minute hand rotates ${fmt(Math.abs(degrees))} degrees clockwise.`:`Signed angle ${fmt(degrees)} degrees. Terminal side: ${position(degrees)}. ${turns} complete turns.`);}
function radianScene(svg,r,theta){const R=40*r,degrees=theta*180/Math.PI,[sx,sy]=point(R+30,degrees/2),[tx,ty]=point(Math.max(12,R*.4),degrees/2);svg.setAttribute('aria-label',`Radius ${fmt(r)}, arc length ${fmt(r*theta)}, central angle ${fmt(theta)} radians.`);svg.innerHTML=`<circle cx="250" cy="250" r="${R}" fill="none" stroke="var(--line)" stroke-width="2"/><path d="M250 250 L${250+R} 250 ${arc(R,0,degrees).replace(/^M[^L]+/,'')} Z" fill="rgba(255,107,72,.1)"/>${ray(R,0,'var(--gold)',5)}${ray(R,degrees,'var(--green)',3)}<path d="${arc(R,0,degrees)}" fill="none" stroke="var(--coral)" stroke-width="7"/><path d="${arc(Math.min(48,R*.6),0,degrees)}" fill="none" stroke="var(--violet)" stroke-width="2"/><circle cx="250" cy="250" r="5" fill="var(--ink)"/><text class="angle-label" x="${250+R/2}" y="278" text-anchor="middle">r = ${fmt(r)}</text><text class="angle-label" x="${sx}" y="${sy-8}" text-anchor="middle">s = ${fmt(r*theta)}</text><text class="angle-label" x="${tx}" y="${ty-12}" text-anchor="middle">θ</text>`;}
radianScene($('angle-hero-chart'),3.5,1);
let animation=null,playing=false,lastTime=0;
function renderTurn(){const degrees=Number($('turn-angle').value),turns=Math.floor(Math.abs(degrees)/360),remainder=Math.abs(degrees)%360;$('turn-angle-value').textContent=fmt(degrees)+'°';circleScene($('turn-chart'),degrees);$('turn-reading').innerHTML=`<strong>${position(degrees)}</strong><p>${degrees===0?'No rotation.':degrees>0?'Counterclockwise: positive rotation.':'Clockwise: negative rotation.'}</p><p>${M(`${degrees}^\\circ=${degreePi(degrees)}`)}</p><p>${turns} complete turn${turns===1?'':'s'} + ${fmt(remainder)}° remaining. The terminal position is ${M(`${fmt(normalized(degrees))}^\\circ`)} within one positive turn.</p>`;}
function stopTurn(){playing=false;if(animation!==null)cancelAnimationFrame(animation);animation=null;$('turn-play').textContent='Animate a turn';$('turn-play').setAttribute('aria-pressed','false');}
$('turn-play').setAttribute('aria-pressed','false');$('turn-play').addEventListener('click',()=>{if(playing){stopTurn();return;}if(matchMedia('(prefers-reduced-motion: reduce)').matches){$('turn-angle').value=Number($('turn-angle').value)>=990?-720:Number($('turn-angle').value)+90;renderTurn();return;}playing=true;lastTime=0;$('turn-play').textContent='Pause rotation';$('turn-play').setAttribute('aria-pressed','true');const frame=time=>{if(!playing)return;if(!lastTime)lastTime=time;const elapsed=(time-lastTime)/1000;if(elapsed>=1/30){let next=Number($('turn-angle').value)+Math.max(1,Math.round(elapsed*45));if(next>1080)next=-720;$('turn-angle').value=next;renderTurn();lastTime=time;}animation=requestAnimationFrame(frame);};animation=requestAnimationFrame(frame);});
$('turn-angle').addEventListener('input',()=>{stopTurn();renderTurn();});document.querySelectorAll('[data-turn]').forEach(btn=>btn.addEventListener('click',()=>{stopTurn();$('turn-angle').value=btn.dataset.turn;renderTurn();}));document.addEventListener('visibilitychange',()=>{if(document.hidden)stopTurn();});renderTurn();
function renderRadian(){const r=Number($('radian-radius').value),theta=Number($('radian-theta').value),s=r*theta,max=Math.max(r,s)||1;$('radian-radius-value').textContent=fmt(r);$('radian-theta-value').textContent=fmt(theta)+' rad';radianScene($('radian-chart'),r,theta);$('radian-reading').innerHTML=`<p>${M(String.raw`s=r\theta=${r}(${theta.toFixed(4)})\approx${s.toFixed(4)}`)}</p><p>${M(String.raw`\theta=\frac{s}{r}\approx${theta.toFixed(4)}\ \text{rad}`)}</p><strong>${Math.abs(theta-1)<1e-8?'One radian: s and r have equal length.':`This is approximately ${fmt(theta*180/Math.PI)}°.`}</strong><p>The lengths use the same unit. Displayed decimals are rounded.</p>`;$('radian-bars').innerHTML=`<div><span>Radius r</span><i style="width:${r/max*100}%;background:var(--gold)"></i><b>${fmt(r)}</b></div><div><span>Arc s</span><i style="width:${s/max*100}%;background:var(--coral)"></i><b>${fmt(s)}</b></div>`;}
['radian-radius','radian-theta'].forEach(id=>$(id).addEventListener('input',renderRadian));document.querySelectorAll('[data-radian]').forEach(btn=>btn.addEventListener('click',()=>{$('radian-theta').value=btn.dataset.radian;renderRadian();}));renderRadian();
function renderConversion(){const mode=$('convert-mode').value;$('convert-degree-controls').hidden=mode!=='degrees';$('convert-pi-controls').hidden=mode!=='pi';if(mode==='degrees'){const deg=$('convert-degrees').valueAsNumber;if(!Number.isFinite(deg)||Math.abs(deg)>1000000||Math.abs(deg*1000000-Math.round(deg*1000000))>1e-4){$('convert-reading').innerHTML='<p>Enter degrees between −1,000,000 and 1,000,000, with at most six decimal places.</p>';return;}$('convert-reading').innerHTML=`<p class="tool-label">Degrees → radians</p><div class="laws-equation">${M(String.raw`${deg}^\circ\cdot\frac{\pi\ \text{rad}}{180^\circ}=${degreePi(deg)}\ \text{rad}`)}</div><p>The degree units cancel. Reduce the fraction and keep π for an exact answer.</p><p>Approximate radian value: ${fmt(deg*Math.PI/180,6)}.</p>`;}else{const n=$('convert-n').valueAsNumber,d=$('convert-d').valueAsNumber;if(!Number.isInteger(n)||!Number.isInteger(d)||d===0||Math.abs(n)>1000000||Math.abs(d)>1000000){$('convert-reading').innerHTML='<p>Use whole-number coefficients between −1,000,000 and 1,000,000. The denominator cannot be zero.</p>';return;}const [N,D]=rational(n*180,d);$('convert-reading').innerHTML=`<p class="tool-label">Radians → degrees</p><div class="laws-equation">${M(String.raw`${piFraction(n,d)}\ \text{rad}\cdot\frac{180^\circ}{\pi\ \text{rad}}=${fraction(N,D)}^\circ`)}</div><p>π and the radian units cancel. This is approximately ${fmt(N/D,6)}°.</p>`;}}
['convert-mode','convert-degrees','convert-n','convert-d'].forEach(id=>$(id).addEventListener($(id).tagName==='SELECT'?'change':'input',renderConversion));$('convert-example-deg').addEventListener('click',()=>{$('convert-mode').value='degrees';$('convert-degrees').value=800;renderConversion();});$('convert-example-pi').addEventListener('click',()=>{$('convert-mode').value='pi';$('convert-n').value=13;$('convert-d').value=12;renderConversion();});document.querySelectorAll('[data-common]').forEach(btn=>btn.addEventListener('click',()=>{$('convert-mode').value='degrees';$('convert-degrees').value=btn.dataset.common;renderConversion();}));renderConversion();
function renderCoterminal(){const base=$('co-base').valueAsNumber,k=Number($('co-k').value),test=$('co-test').valueAsNumber;$('co-k-value').textContent=k;if(!Number.isFinite(base)||Math.abs(base)>1000000){$('co-reading').innerHTML='<p>Enter a starting angle between −1,000,000° and 1,000,000°.</p>';$('co-examples').innerHTML='';$('co-chart').innerHTML='';$('co-feedback').textContent='';return;}const candidate=base+360*k,principal=normalized(base);circleScene($('co-chart'),candidate%360);$('co-chart').insertAdjacentHTML('beforeend',`<text class="angle-label" x="250" y="480" text-anchor="middle">Shared terminal side: ${position(base)}</text>`);$('co-reading').innerHTML=`<p>${M(String.raw`${base}^\circ+360^\circ(${k})=${candidate}^\circ`)}</p><p>${M(String.raw`${degreePi(base)}+2\pi(${k})=${degreePi(candidate)}`)}</p><strong>Same terminal side: ${position(base)}</strong>`;let p=principal===0?360:principal;if(Math.abs(p-base)<1e-8)p+=360;const neg=principal-360;$('co-examples').innerHTML=`<article><strong>Two positive examples</strong><p>${M(`${fmt(p)}^\\circ,\\quad ${fmt(p+360)}^\\circ`)}</p><p>${M(`${degreePi(p)},\\quad ${degreePi(p+360)}`)}</p></article><article><strong>Two negative examples</strong><p>${M(`${fmt(neg)}^\\circ,\\quad ${fmt(neg-360)}^\\circ`)}</p><p>${M(`${degreePi(neg)},\\quad ${degreePi(neg-360)}`)}</p></article>`;if(!Number.isFinite(test)||Math.abs(test)>1000000){$('co-feedback').classList.remove('is-correct','is-incorrect');$('co-feedback').textContent='Enter a finite test angle within ±1,000,000°.';return;}const turns=(test-base)/360,ok=Math.abs(turns-Math.round(turns))<1e-9;setFeedback($('co-feedback'),ok,ok?`Coterminal: the difference is ${fmt(turns)} whole turns.`:`Different terminal sides: the difference is ${fmt(turns)} turns, not an integer.`);}
['co-base','co-k','co-test'].forEach(id=>$(id).addEventListener('input',renderCoterminal));document.querySelectorAll('[data-co]').forEach(btn=>btn.addEventListener('click',()=>{$('co-base').value=btn.dataset.co;$('co-k').value=0;renderCoterminal();}));renderCoterminal();
function renderClock(){const minutes=Number($('clock-minutes').value),degrees=6*minutes;$('clock-minutes-value').textContent=minutes;circleScene($('clock-chart'),-degrees,{axes:false,start:90,clock:true});$('clock-reading').innerHTML=`<p>Angular distance:</p><div class="laws-equation">${M(`${minutes}\\cdot6^\\circ=${degrees}^\\circ=${piFraction(minutes,30)}\\ \\text{rad}`)}</div><p>Signed clockwise rotation:</p><div class="laws-equation">${M(`${-degrees}^\\circ=${piFraction(-minutes,30)}\\ \\text{rad}`)}</div><p>${minutes===1?'In one minute, the hand travels 6° = π/30 radians.':`${Math.floor(minutes/60)} full turn(s), then ${minutes%60} more minutes.`}</p>`;}
$('clock-minutes').addEventListener('input',renderClock);renderClock();
const solved=new Set();document.querySelectorAll('[data-angle-check]').forEach(btn=>btn.addEventListener('click',()=>{const i=Number(btn.dataset.angleCheck),input=document.querySelector(`[name="angle-practice-${i}"]:checked`);if(!input){setFeedback($('angle-feedback-'+i),false,'Choose an answer first.');return;}const correct=Number(input.value)===checks[i][3];if(correct)solved.add(i);setFeedback($('angle-feedback-'+i),correct,(correct?'Correct. ':'Try again. ')+checks[i][4]);$('angle-score').textContent=`${solved.size} of ${checks.length} checks solved${solved.size===checks.length?' · Ready to move on!':''}`;}));
initLessonChrome();
