import "../assets/sass/lesson.sass";
import { renderMathDropdown, initMathDropdown } from "./math-dropdown";
import katex from "katex";
import "katex/dist/katex.min.css";
import { initLessonChrome, renderLessonHeader, renderLessonFooter, setFeedback } from "./shared";

const M = (tex, displayStyle = false) => `<span class="laws-math">${katex.renderToString((displayStyle ? String.raw`\displaystyle ` : "") + tex, { throwOnError: true, strict: "ignore" })}</span>`;
const practiceMath = tex => {
  const text = tex.match(/^\\text\{([^{}]*)\}$/);
  return text ? `<span class="math-dropdown-text">${text[1]}</span>` : M(tex, true);
};
const $ = id => document.getElementById(id);
const fmt = (n, places = 4) => Number(n.toFixed(places)).toString().replaceAll("-", "−");
const intro = (n, topic, title, text) => `<div class="lesson-section__intro" data-reveal><p class="lesson-kicker"><span>${n}</span> ${topic}</p><h2>${title}</h2><p>${text}</p></div>`;
const range = (id, title, min, max, step, value) => `<label for="${id}">${title}<output id="${id}-value"></output></label><input type="range" id="${id}" min="${min}" max="${max}" step="${step}" value="${value}">`;
const selected = id => Number($(id).dataset.value);
const button = (id, text) => `<button class="laws-button" id="${id}" type="button">${text}</button>`;
const stepsUI = (id) => `<div class="laws-step-buttons">${button(`${id}-back`,"← Back")}${button(`${id}-next`,"Next step →")}</div><p class="laws-progress" id="${id}-progress" aria-live="polite"></p>`;
const bind = (ids, render) => { ids.forEach(id=>$(id).addEventListener($(id).type==='range'||$(id).type==='number'?'input':'change',render));render(); };

const ruleNames = ["Product", "Quotient", "Power"];
const ruleTex = [String.raw`\log_a(xy)=\log_a x+\log_a y`, String.raw`\log_a\!\left(\frac{x}{y}\right)=\log_a x-\log_a y`, String.raw`\log_a(x^p)=p\log_a x`];
const proofs = [
 [[String.raw`u=\log_a x,\quad v=\log_a y`,"Read logarithms as exponents."],[String.raw`x=a^u,\quad y=a^v`,"Convert to exponential form."],[String.raw`xy=a^u a^v=a^{u+v}`,"Multiplying equal bases adds their exponents."],[String.raw`\log_a(xy)=u+v=\log_a x+\log_a y`,"Take log base a to recover the exponent."]],
 [[String.raw`x=a^u,\quad y=a^v`,"Let u = logₐx and v = logₐy."],[String.raw`\frac{x}{y}=\frac{a^u}{a^v}=a^{u-v}`,"Dividing equal bases subtracts their exponents."],[String.raw`\log_a\!\left(\frac{x}{y}\right)=u-v`,"The logarithm returns the exponent."],[String.raw`\log_a\!\left(\frac{x}{y}\right)=\log_a x-\log_a y`,"Substitute the definitions of u and v."]],
 [[String.raw`u=\log_a x\quad\Longrightarrow\quad x=a^u`,"Name the exponent that gives x."],[String.raw`x^p=(a^u)^p=a^{up}`,"Raising a power to a power multiplies the exponents."],[String.raw`\log_a(x^p)=up`,"Take a logarithm with the matching base."],[String.raw`\log_a(x^p)=p\log_a x`,"The exponent becomes a coefficient."]],
];
const expansions = [
 {tex:String.raw`\ln\sqrt{ab}`,domain:String.raw`a>0,\ b>0`,full:String.raw`ab>0`,general:String.raw`\frac12\ln|a|+\frac12\ln|b|`,steps:[[String.raw`\ln\big((ab)^{1/2}\big)`,"Rewrite the square root as a one-half power."],[String.raw`\frac12\ln(ab)`,"Use the power rule."],[String.raw`\frac12(\ln a+\ln b)`,"Use the product rule inside the parentheses."],[String.raw`\frac12\ln a+\frac12\ln b`,"Distribute the coefficient to both terms."]]},
 {tex:String.raw`\log_3\!\left(\frac{\sqrt{3x^5}}{y}\right)`,domain:String.raw`x>0,\ y>0`,full:String.raw`x>0,\ y>0`,steps:[[String.raw`\log_3\sqrt{3x^5}-\log_3 y`,"A quotient becomes a difference."],[String.raw`\frac12\log_3(3x^5)-\log_3 y`,"The square root contributes a coefficient of one-half."],[String.raw`\frac12(\log_3 3+5\log_3 x)-\log_3 y`,"Split the product, then move the exponent 5 out."],[String.raw`\frac12+\frac52\log_3 x-\log_3 y`,"Evaluate log₃3 = 1 and distribute one-half."]]},
 {tex:String.raw`\log\!\left(\frac{x^2}{yz^3}\right)`,domain:String.raw`x>0,\ y>0,\ z>0`,full:String.raw`x\ne0,\ yz^3>0`,general:String.raw`2\log|x|-\log|y|-3\log|z|`,steps:[[String.raw`\log(x^2)-\log(yz^3)`,"Apply the quotient rule."],[String.raw`2\log x-(\log y+\log(z^3))`,"Use the power rule on x² and product rule on the denominator."],[String.raw`2\log x-(\log y+3\log z)`,"Move the exponent 3 outside its logarithm."],[String.raw`2\log x-\log y-3\log z`,"Subtract every denominator term. Keep the minus sign on both."]]},
 {tex:String.raw`\log\!\left(\frac{x}{\sqrt[3]{1-x}}\right)`,domain:String.raw`0<x<1`,full:String.raw`0<x<1`,steps:[[String.raw`\log x-\log\big((1-x)^{1/3}\big)`,"A quotient becomes a difference. Write the cube root as a power."],[String.raw`\log x-\frac13\log(1-x)`,"Use the power rule on the entire expression 1 − x."],[String.raw`\boxed{\log x-\frac13\log(1-x)}`,"Stop here. A subtraction inside a log cannot be split."],[String.raw`x>0,\quad 1-x>0\quad\Longrightarrow\quad 0<x<1`,"The original quotient is positive only between zero and one."]]},
];
const claims = [String.raw`\log_2(x+y)=\log_2 x+\log_2 y`,String.raw`\log_2(xy)=(\log_2 x)(\log_2 y)`,String.raw`\log_2(x/y)=\frac{\log_2 x}{\log_2 y}`];
const exacts = [
 {tex:String.raw`\log_3 100-\log_3 18-\log_3 50`,steps:[[String.raw`\log_3\!\left(\frac{100}{18\cdot50}\right)`,"Two subtracted logarithms create two denominator factors."],[String.raw`\log_3\!\left(\frac19\right)`,"Simplify the fraction before evaluating."],[String.raw`\log_3(3^{-2})=-2`,"The matching logarithm returns the exponent −2."]]},
 {tex:String.raw`\log_4(16^{100})`,steps:[[String.raw`100\log_4 16`,"Move the exponent outside."],[String.raw`100\log_4(4^2)`,"Write 16 as a power of the base."],[String.raw`100\cdot2=200`,"Evaluate exactly."]]},
 {tex:String.raw`\log\!\left(\log(10^{10000})\right)`,steps:[[String.raw`\log(10000)`,"Work from the inside out: log(10¹⁰⁰⁰⁰) = 10000."],[String.raw`\log(10^4)`,"Write the remaining input as a power of 10."],[String.raw`4`,"The outer logarithm returns 4."]]},
];
const checks = [
 ["Choose the product rule",String.raw`\ln(uv)`,[String.raw`\ln u+\ln v`,String.raw`(\ln u)(\ln v)`,String.raw`\ln u-\ln v`],0,"A product inside a logarithm becomes a sum of logarithms."],
 ["Keep a sum together",String.raw`\log_2(x+y)`,[String.raw`\log_2 x+\log_2 y`,String.raw`\text{No general splitting rule}`,String.raw`\log_2 x\cdot\log_2 y`],1,"A sum inside a logarithm cannot generally be split. Only products, quotients, and powers have these rules."],
 ["Expand a radical",String.raw`\ln\sqrt{ab}\quad(a,b>0)`,[String.raw`\frac12\ln a+\ln b`,String.raw`\frac12\ln a+\frac12\ln b`,String.raw`\ln a+\ln b`],1,"The square root applies to the whole product, so one-half multiplies both logarithms."],
 ["Read the denominator",String.raw`\log\frac{x^2}{yz^3}\quad(x,y,z>0)`,[String.raw`2\log x-\log y+3\log z`,String.raw`2\log x-\log y-3\log z`,String.raw`2\log x-(\log y)(3\log z)`],1,"The entire denominator is subtracted. Both log y and 3 log z have minus signs."],
 ["Stop at a difference",String.raw`\log\frac{x}{\sqrt[3]{1-x}}`,[String.raw`\log x-\frac13\log(1-x)`,String.raw`\log x-\frac13\log1+\frac13\log x`,String.raw`\log x-3\log(1-x)`],0,"The cube root becomes a one-third coefficient. Keep 1 − x intact."],
 ["Combine completely",String.raw`2(\log_5 x+2\log_5 y-3\log_5 z)`,[String.raw`2\log_5\frac{xy^2}{z^3}`,String.raw`\log_5\frac{x^2y^4}{z^6}`,String.raw`\log_5\frac{2xy^2}{z^3}`],1,"A coefficient of 2 becomes a power of the entire quotient. The final logarithm has coefficient 1."],
 ["Undo a natural log",String.raw`e^{2-7\ln x+\ln y}\quad(x,y>0)`,[String.raw`\frac{e^2y}{x^7}`,String.raw`\frac{2y}{x^7}`,String.raw`e^2-7x+y`],0,"Split the exponential into factors, then apply e^(ln x) = x. Keep e²."],
 ["Recover the model",String.raw`\log P=\log c-k\log W`,[String.raw`P=c-kW`,String.raw`P=\frac{c}{W^k}`,String.raw`P=cW^k`],1,"Move k inside as an exponent, combine the difference as a quotient, then undo the logarithm."],
 ["Change the base",String.raw`\log_6 532`,[String.raw`\frac{\ln6}{\ln532}`,String.raw`\ln532-\ln6`,String.raw`\frac{\ln532}{\ln6}`],2,"The input goes on top, and the original base goes on the bottom."],
 ["Check the full domain",String.raw`\ln\sqrt{ab}\quad\text{with }a=b=-2`,[String.raw`\text{Original expression is undefined}`,String.raw`\text{Original is defined; use absolute values to expand}`,String.raw`\frac12\ln(-2)+\frac12\ln(-2)`],1,"The product ab = 4 is positive, so the original is defined. Individual real logs of −2 are undefined; absolute values preserve this case."],
];

document.querySelector("#app").innerHTML = `${renderLessonHeader("4.4")}<main class="laws-lesson">
<section class="lesson-hero lesson-hero--laws"><div class="lesson-hero__copy" data-reveal><p class="lesson-kicker"><span>Section 4.4</span> Laws of logarithms</p><h1>Products become sums.<br><em>Powers come outside.</em></h1><p class="lesson-hero__lede">Logarithms turn multiplication into addition. Learn to unpack complicated inputs, assemble a single logarithm, and see which algebraic moves preserve the meaning.</p><div class="lesson-hero__actions"><a class="lesson-button lesson-button--dark" href="#rules">Explore the rules</a><span>About 40 minutes · interactive</span></div></div><div class="laws-hero-art" data-reveal><p class="tool-label">Same relationship, different arithmetic</p><div class="laws-equation">${M(String.raw`\textcolor{#60419b}{2^3}\cdot\textcolor{#246240}{2^2}=2^{\textcolor{#c5442d}{5}}`)}</div><span class="laws-arrow">↓ take log base 2</span><div class="laws-equation">${M(String.raw`\textcolor{#60419b}{3}+\textcolor{#246240}{2}=\textcolor{#c5442d}{5}`)}</div><p>Multiplication of powers adds exponents.<br>Logarithms reveal those exponents.</p></div></section>
<section class="lesson-objectives" aria-label="Lesson objectives" data-reveal><p>By the end, you can</p><ol><li><span>01</span><p>Use and justify the three logarithm laws</p></li><li><span>02</span><p>Expand and combine with correct signs</p></li><li><span>03</span><p>Evaluate exactly or change the base</p></li><li><span>04</span><p>Recover formulas from logarithmic models</p></li></ol></section>
<section class="lesson-section" id="rules">${intro("01","Understand the rules","One base.<br>Three useful moves.",`For a valid base ${M(String.raw`a>0,\ a\ne1`)} and positive inputs ${M(String.raw`x,y>0`)}, these identities hold. The exponent ${M('p')} may be any real number.`)}<div class="laws-rule-cards">${ruleTex.map((tex,i)=>`<article><p class="tool-label">${ruleNames[i]} rule</p><div class="laws-equation">${M(tex)}</div><p>${["Multiply inputs; add logarithms.","Divide inputs; subtract logarithms.","Raise the input; multiply its logarithm."][i]}</p></article>`).join("")}</div>
<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Living rule explorer</p><label for="rule-kind">Operation</label><select id="rule-kind"><option value="0">Product</option><option value="1">Quotient</option><option value="2">Power</option></select><label for="rule-base">Base</label><select id="rule-base"><option value="2">2</option><option value="10">10</option><option value="0.5">½</option></select>${range("rule-x","Input x",0.25,8,0.25,4)}${range("rule-y","Input y",0.25,8,0.25,2)}${range("rule-p","Power p",-3,3,0.5,2)}</div><div class="laws-result" id="rule-reading" aria-live="polite"></div></div>
<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Why the rules work</p><label for="proof-kind">Choose a derivation</label><select id="proof-kind"><option value="0">Product rule</option><option value="1">Quotient rule</option><option value="2">Power rule</option></select>${stepsUI("proof")}</div><div class="laws-result" id="proof-step" aria-live="polite"></div></div></section>
<section class="lesson-section lesson-section--soft" id="mistakes">${intro("02","Test a tempting move","A logarithm<br>does not distribute.",`There is no general expansion rule for ${M(String.raw`\log_a(x+y)`)} or ${M(String.raw`\log_a(x-y)`)}. Also, a product inside a log becomes a <strong>sum</strong>, not a product of logs.`)}
<div class="laws-lab laws-lab--dropdown" data-reveal><div class="laws-controls"><p class="tool-label">Counterexample detector</p>${renderMathDropdown("mistake-kind","Inspect a claim",claims,tex=>M(tex,true))}${range("mistake-x","Positive x",1,8,1,2)}${range("mistake-y","Positive y",2,8,1,2)}</div><div class="laws-result" id="mistake-reading" aria-live="polite"></div></div><aside class="laws-note"><strong>An accidental match is not a law.</strong> Some inputs can make a false identity look true. Change the values; one counterexample disproves a proposed general rule.</aside></section>
<section class="lesson-section" id="expand">${intro("03","Work it out","Unpack the input.<br>Keep every sign.","First separate a quotient. Then separate products, and move powers to the outside. Roots are fractional powers. Stop when a log input contains a sum or difference.")}
<div class="laws-lab laws-lab--dropdown" data-reveal><div class="laws-controls"><p class="tool-label">Expansion workshop</p>${renderMathDropdown("expand-case","Choose an expression",expansions.map(c=>c.tex),tex=>M(tex,true))}<div class="laws-note" id="expand-domain"></div>${stepsUI("expand")}</div><div class="laws-result" id="expand-step" aria-live="polite"></div></div><aside class="laws-note" id="expand-full" aria-live="polite"></aside></section>
<section class="lesson-section lesson-section--soft" id="combine">${intro("04","Explore the reverse direction","Build one logarithm.<br>Give it coefficient one.","Move coefficients inside as powers. Sums become products, differences become quotients. A coefficient outside parentheses multiplies every exponent in the final input. Use the same logarithm base throughout.")}
<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Single-log assembler</p>${range("combine-m","Outside multiplier m",1,3,1,2)}${range("combine-p","Coefficient of log₅x",1,4,1,1)}${range("combine-q","Coefficient of log₅y",1,4,1,2)}${range("combine-r","Subtracted coefficient of log₅z",1,4,1,3)}<p>Assume ${M('x,y,z>0')}.</p>${stepsUI("combine")}</div><div class="laws-result" id="combine-step" aria-live="polite"></div></div></section>
<section class="lesson-section" id="evaluate">${intro("05","Evaluate deliberately","Simplify first.<br>Calculate only when needed.","An exact answer often appears after combining logarithms or rewriting an input as a power of the base. Nested logarithms are evaluated from the inside out.")}
<div class="laws-lab laws-lab--dropdown" data-reveal><div class="laws-controls"><p class="tool-label">Exact-value workshop</p>${renderMathDropdown("exact-case","Choose an expression",exacts.map(c=>c.tex),tex=>M(tex,true))}${stepsUI("exact")}</div><div class="laws-result" id="exact-step" aria-live="polite"></div></div>
<div class="laws-change-proof" data-reveal><p class="tool-label">Derive change of base</p><p class="laws-change-steps">${M(String.raw`y=\log_b x`)}${M(String.raw`\Longrightarrow\ b^y=x`)}${M(String.raw`\Longrightarrow\ y\ln b=\ln x`)}</p><div class="laws-change-result"><div class="laws-change-lead">${M(String.raw`\displaystyle \log_{\color{#c4482a}b}{\color{#28603a}x}`)}</div><div class="laws-change-equivalents">${M(String.raw`\displaystyle =\frac{\ln{\color{#28603a}x}}{\ln{\color{#c4482a}b}}=\frac{\log{\color{#28603a}x}}{\log{\color{#c4482a}b}}`)}</div></div><p>Any valid new base works. The input goes on top; the original base goes on the bottom.</p></div>
<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Change-of-base calculator</p><label for="change-b">Original base b</label><input type="number" id="change-b" value="6" step="any"><label for="change-x">Positive input x</label><input type="number" id="change-x" value="532" step="any"><p>Use ${M(String.raw`b>0,\ b\ne1,\ x>0`)}. Keep full precision until the final answer.</p></div><div class="laws-result" id="change-result" aria-live="polite"></div></div></section>
<section class="lesson-section lesson-section--soft" id="models">${intro("06","Undo the logarithms","From log language<br>back to a model.",`Combine the logarithms before applying an inverse operation. For instance, ${M(String.raw`\ln y=2\ln x+\ln5`)} gives ${M(String.raw`y=5x^2`)}, because ${M(String.raw`\ln y=\ln(5x^2)`)}, assuming ${M('x,y>0')}.`)}
<div class="laws-card-grid"><article class="laws-card"><p class="tool-label">An exponential with logarithms inside</p><div class="laws-equation">${M(String.raw`e^{2-7\ln x+\ln y}`)}</div><p>Assume ${M('x,y>0')}. Predict the simplified expression, then reveal the reasoning.</p>${button("unlog-show","Undo the logarithms")}<div id="unlog-work" class="laws-note" hidden>${M(String.raw`e^2\cdot e^{-7\ln x}\cdot e^{\ln y}`)}<p>${M(String.raw`=e^2 x^{-7}y=\frac{e^2y}{x^7}`)}</p><p>The constant 2 stays in an exponential. Only matching exponential/logarithm pairs cancel.</p></div></article><article class="laws-card"><p class="tool-label">Two recurring model patterns</p><div class="laws-equation">${M(String.raw`\log S=\log c+k\log A`)}</div><p>${M(String.raw`S=cA^k`)}: a positive power model.</p><div class="laws-equation">${M(String.raw`\log P=\log c-k\log W`)}</div><p>${M(String.raw`P=\frac{c}{W^k}`)}: an inverse power model.</p><p>All model inputs and constants are positive.</p></article></div>
<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Power-model explorer</p><label for="model-kind">Context</label><select id="model-kind"><option value="species">Species and habitat area</option><option value="wealth">Population above a wealth threshold</option></select>${range("model-input","Input",1,20,0.5,2)}${range("model-k","Exponent k",0.1,3,0.1,0.3)}<p id="model-units"></p>${button("model-preset","Try the inverse-power model")}</div><div class="laws-result" id="model-reading" aria-live="polite"></div></div></section>
<section class="lesson-section lesson-section--ink" id="readiness">${intro("07","Practice","Choose the move.<br>Explain why it works.","Use the input structure, coefficient, and domain to decide. These checks cover expansion, combination, evaluation, and model recovery.")}<p class="laws-score" id="laws-score" aria-live="polite">0 of ${checks.length} checks solved</p><div class="laws-check-grid">${checks.map((q,i)=>`<article class="laws-check"><p class="tool-label">${q[0]}</p><h3>${M(q[1])}</h3>${renderMathDropdown(`practice-${i}`,"Your answer",q[2],practiceMath,{placeholder:"Select an answer"})}<button class="laws-button" type="button" data-check="${i}">Check answer</button><p class="answer-feedback" id="feedback-${i}" aria-live="polite"></p></article>`).join("")}</div></section>
</main>${renderLessonFooter({previous:{href:"pages/sections/4-3.html",label:"Section 4.3 · Logarithmic functions"},next:{href:"pages/sections/4-5.html",label:"Section 4.5 · Exponential and logarithmic equations"}})}`;

bind(["rule-kind","rule-base","rule-x","rule-y","rule-p"],()=>{
 const kind=Number($("rule-kind").value),b=Number($("rule-base").value),x=Number($("rule-x").value),y=Number($("rule-y").value),p=Number($("rule-p").value),L=v=>Math.log(v)/Math.log(b);
 ["x","y","p"].forEach(v=>$("rule-"+v+"-value").textContent=fmt({x,y,p}[v]));
 $("rule-y").disabled=kind===2;$("rule-p").disabled=kind!==2;
 const left=[L(x*y),L(x/y),L(x**p)][kind],a=L(x),c=kind===2?p:L(y),right=[a+c,a-c,a*c][kind];
 const formula=[String.raw`\log_{${b}}(${x}\cdot${y})=\log_{${b}}${x}+\log_{${b}}${y}`,String.raw`\log_{${b}}\!\left(\frac{${x}}{${y}}\right)=\log_{${b}}${x}-\log_{${b}}${y}`,String.raw`\log_{${b}}(${x}^{${p}})=${p}\log_{${b}}${x}`][kind];
 $("rule-reading").innerHTML=`<p class="tool-label">${ruleNames[kind]} rule in action</p><div class="laws-equation">${M(formula)}</div><div class="laws-number-tiles"><div><span>Left side</span><strong>${fmt(left)}</strong></div><div><span>Right side</span><strong>${fmt(right)}</strong></div></div><p>${M(`${fmt(a)} ${kind===0?'+':kind===1?'-':String.raw`\times`} ${fmt(c)} = ${fmt(left)}`)}</p><p>${kind===2?"The exponent multiplies the logarithm; it does not multiply the input.":"The two readings give the same real number, even when an individual logarithm is negative."}</p><div class="laws-meter"><span>0</span><i style="--meter-position:${50+Math.max(-45,Math.min(45,left*45/8))}%"></i></div><p class="laws-caption">The marker shows the signed logarithm value on a fixed scale from −8 to 8. Values beyond that scale remain at the edge.</p>`;
});
function stepper(id,changeIds,getSteps,onRender){
 let index=0;
 const render=()=>{const steps=getSteps();onRender(steps[index],index);$(id+"-back").disabled=index===0;$(id+"-next").disabled=index===steps.length-1;$(id+"-progress").textContent=`Step ${index+1} of ${steps.length}`;};
 $(id+"-back").addEventListener("click",()=>{if(index>0)index--;render();});$(id+"-next").addEventListener("click",()=>{if(index<getSteps().length-1)index++;render();});
 changeIds.forEach(key=>$(key).addEventListener($(key).type==='range'?'input':'change',()=>{index=0;render();}));render();
}
const stepMarkup=(step,index)=>`<p class="tool-label">Move ${index+1}</p><div class="laws-equation">${M(step[0])}</div><p>${step[1]}</p>`;
stepper("proof",["proof-kind"],()=>proofs[Number($("proof-kind").value)],(step,i)=>$("proof-step").innerHTML=stepMarkup(step,i));
initMathDropdown("mistake-kind",claims,tex=>M(tex,true));
bind(["mistake-kind","mistake-x","mistake-y"],()=>{
 const kind=selected("mistake-kind"),x=Number($("mistake-x").value),y=Number($("mistake-y").value),L=Math.log2;
 $("mistake-x-value").textContent=x;$("mistake-y-value").textContent=y;
 const lhs=[L(x+y),L(x*y),L(x/y)][kind],rhs=[L(x)+L(y),L(x)*L(y),L(x)/L(y)][kind],match=Math.abs(lhs-rhs)<1e-9;
 $("mistake-reading").innerHTML=`<p class="tool-label">Test x = ${x}, y = ${y}</p><div class="laws-number-tiles"><div><span>Original expression</span><strong>${fmt(lhs)}</strong></div><div><span>Claimed rewrite</span><strong>${fmt(rhs)}</strong></div></div><div class="laws-note ${match?'':'laws-note--coral'}"><strong>${match?"These inputs happen to match.":"Different values: this claim is false."}</strong><p>${match?"Try x = 3, y = 2. A rule must work for every allowed input.":"This one counterexample is enough to disprove the general claim."}</p></div><p>${kind===0?`The input is a sum, so keep ${M(String.raw`\log_2(x+y)`)} intact.`:`The correct identity is ${M(ruleTex[kind===1?0:1].replaceAll('_a','_2'))}.`}</p>`;
});
initMathDropdown("expand-case",expansions.map(c=>c.tex),tex=>M(tex,true));
stepper("expand",["expand-case"],()=>expansions[selected("expand-case")].steps,(step,i)=>{
 const c=expansions[selected("expand-case")];$("expand-step").innerHTML=stepMarkup(step,i);$("expand-domain").innerHTML=`<strong>For this expansion, assume</strong><p>${M(c.domain)}</p>`;
 $("expand-full").innerHTML=`<strong>Original real domain:</strong> ${M(c.full)}. ${c.general?`To preserve every original input, use ${M(c.general)}. Absolute values allow negative factors whose product or quotient is positive.`:"These restrictions also make each logarithm in the expansion legal."}`;
});
function combineSteps(){
 const values={};["m","p","q","r"].forEach(key=>{values[key]=Number($("combine-"+key).value);$("combine-"+key+"-value").textContent=values[key];});const {m,p,q,r}=values;
 return [[String.raw`${m}\big(${p}\log_5x+${q}\log_5y-${r}\log_5z\big)`,"Start with the coefficients and the outside multiplier."],[String.raw`${m}\left(\log_5(x^{${p}})+\log_5(y^{${q}})-\log_5(z^{${r}})\right)`,"Reverse the power rule: coefficients become exponents."],[String.raw`${m}\log_5\!\left(\frac{x^{${p}}y^{${q}}}{z^{${r}}}\right)`,"Combine sums as products and the difference as a quotient."],[String.raw`\log_5\!\left(\frac{x^{${m*p}}y^{${m*q}}}{z^{${m*r}}}\right)`,"Move the outside multiplier into the entire quotient. The coefficient is now 1."]];
}
stepper("combine",["combine-m","combine-p","combine-q","combine-r"],combineSteps,(step,i)=>$("combine-step").innerHTML=stepMarkup(step,i));
initMathDropdown("exact-case",exacts.map(c=>c.tex),tex=>M(tex,true));
stepper("exact",["exact-case"],()=>exacts[selected("exact-case")].steps,(step,i)=>$("exact-step").innerHTML=stepMarkup(step,i));
bind(["change-b","change-x"],()=>{
 const b=$("change-b").valueAsNumber,x=$("change-x").valueAsNumber;
 if(!Number.isFinite(b)||!Number.isFinite(x)||b<=0||b===1||x<=0){$("change-result").innerHTML=`<div class="laws-note laws-note--coral"><strong>Choose a valid base and input.</strong><p>The base must be positive and different from 1. The input must be strictly positive. Fill both fields with finite numbers.</p></div>`;return;}
 const value=Math.log(x)/Math.log(b);$("change-result").innerHTML=`<p class="tool-label">Same result in two calculator bases</p><div class="laws-equation">${M(String.raw`\log_{${b}}${x}=\frac{\ln(${x})}{\ln(${b})}`)}</div><div class="laws-equation">${M(String.raw`=\frac{\log(${x})}{\log(${b})}\approx ${value.toFixed(6)}`)}</div><p>Rounded to six decimal places. ${b<1?"With a base below 1, logarithms reverse direction: inputs above 1 have negative logarithms.":"Round the final quotient, not the separate logarithms."}</p>`;
});
$("unlog-show").addEventListener("click",()=>{$("unlog-work").hidden=!$("unlog-work").hidden;$("unlog-show").textContent=$("unlog-work").hidden?"Undo the logarithms":"Hide the reasoning";});
function renderModel(){
 const wealth=$("model-kind").value==='wealth',x=Number($("model-input").value),k=Number($("model-k").value),c=wealth?8000:12,value=c*x**(wealth?-k:k);
 $("model-input-value").textContent=fmt(x);$("model-k-value").textContent=fmt(k);$("model-units").textContent=wealth?"W is a wealth threshold in millions of dollars. P estimates people at or above that threshold; c = 8000.":"A is habitat area in square kilometers. S estimates species; c = 12. These are illustrative models.";
 const baseValue=c,ratio=value/baseValue;
 $("model-reading").innerHTML=`<p class="tool-label">${wealth?"Inverse":"Positive"} power model</p><div class="laws-equation">${M(wealth?String.raw`P=\frac{8000}{W^{${k}}}`:String.raw`S=12A^{${k}}`)}</div><div class="laws-model-value"><strong>${Math.round(value).toLocaleString('en-US')}</strong><span>estimated ${wealth?'people':'species'}</span></div><p>${M(wealth?String.raw`P(${x})=\frac{8000}{${x}^{${k}}}\approx${value.toFixed(2)}`:String.raw`S(${x})=12(${x})^{${k}}\approx${value.toFixed(2)}`)}</p><div class="laws-model-bars"><div><span>Input = 1</span><i style="width:${100/(Math.max(1,ratio))}%"></i><b>${c}</b></div><div><span>Input = ${fmt(x)}</span><i style="width:${100*ratio/(Math.max(1,ratio))}%"></i><b>${fmt(value,1)}</b></div></div><p>${wealth?"Raising the threshold reduces the predicted population. At k = 2.1, compare thresholds of 2 and 10 million dollars.":"Area increases the predicted species count. At k below 1, multiplying area gives a smaller proportional increase in species."} Displayed counts are rounded estimates.</p>`;
}
bind(["model-kind","model-input","model-k"],renderModel);
$("model-kind").addEventListener("change",()=>{$("model-k").value=$("model-kind").value==='wealth'?2.1:0.3;renderModel();});
$("model-preset").addEventListener("click",()=>{$("model-kind").value='wealth';$("model-k").value=2.1;$("model-input").value=2;renderModel();});
checks.forEach((q,i)=>initMathDropdown(`practice-${i}`,q[2],practiceMath));
const solved=new Set();
document.querySelectorAll('[data-check]').forEach(btn=>btn.addEventListener('click',()=>{const i=Number(btn.dataset.check),value=$("practice-"+i).dataset.value;if(value===""){setFeedback($("feedback-"+i),false,"Choose an answer before checking.");return;}const correct=Number(value)===checks[i][3];if(correct)solved.add(i);setFeedback($("feedback-"+i),correct,(correct?"Correct. ":"Try again. ")+checks[i][4]);$("laws-score").textContent=`${solved.size} of ${checks.length} checks solved${solved.size===checks.length?' · Ready to move on!':''}`;}));
initLessonChrome();
