import "../assets/sass/lesson.sass";
import {renderMathDropdown, initMathDropdown} from "./math-dropdown";
import katex from "katex";
import "katex/dist/katex.min.css";
import { initLessonChrome, renderLessonHeader, renderLessonFooter, setFeedback } from "./shared";

const M = tex => `<span class="laws-math">${katex.renderToString(String.raw`\displaystyle `+tex,{throwOnError:true,strict:"ignore"})}</span>`;
const $ = id => document.getElementById(id);
const fmt = (value,digits=4) => Number(value.toFixed(digits)).toString().replaceAll('-','−');
const intro=(n,topic,title,text)=>`<div class="lesson-section__intro" data-reveal><p class="lesson-kicker"><span>${n}</span> ${topic}</p><h2>${title}</h2><p>${text}</p></div>`;
const range=(id,title,min,max,step,value)=>`<label for="${id}">${title}<output id="${id}-value"></output></label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}">`;
const choices=(id,title,items)=>renderMathDropdown(id,title,items,M);
const selected=id=>Number($(id).dataset.value);
const stepUI=id=>`<div class="laws-step-buttons"><button type="button" class="laws-button" id="${id}-back">← Back</button><button type="button" class="laws-button" id="${id}-next">Next step →</button></div><p id="${id}-progress" class="laws-progress" aria-live="polite"></p>`;
const classification=[
 [String.raw`x^3-2=25`,"neither","The variable is neither an exponent nor a logarithm input. This is a polynomial equation."],
 [String.raw`\log_5(14+e^2)=x`,"neither","The logarithm's input is a constant. The unknown stands alone on the right."],
 [String.raw`3(0.75)^{2x}-2=5`,"exponential","The variable appears in an exponent. Isolate the exponential before taking logarithms."],
 [String.raw`\log_{1/2}(2+x^2)=-6`,"logarithmic","The variable appears inside the logarithm's input. Convert to exponential form, then solve the quadratic."],
];
const exponentialCases=[
 {tex:String.raw`5^{x-1}=125`,steps:[[String.raw`5^{x-1}=5^3`,"Rewrite 125 using the same base."],[String.raw`x-1=3`,"A valid exponential base is one-to-one, so equal powers have equal exponents."],[String.raw`x=4`,"Solve and check: 5³ = 125."]]},
 {tex:String.raw`10^{2x^2-3}=\frac1{10^{x^2-9}}`,steps:[[String.raw`10^{2x^2-3}=10^{9-x^2}`,"A reciprocal changes the sign of the entire exponent."],[String.raw`2x^2-3=9-x^2`,"Equate exponents of the common base."],[String.raw`3x^2=12\quad\Longrightarrow\quad x^2=4`,"Collect like terms."],[String.raw`x=-2\quad\text{or}\quad x=2`,"Keep both square roots. Both make the exponents equal to 5."]]},
 {tex:String.raw`3^{2x-1}=5`,steps:[[String.raw`(2x-1)\ln3=\ln5`,"Take ln of both positive sides and apply the power rule."],[String.raw`2x-1=\frac{\ln5}{\ln3}=\log_3 5`,"Divide by ln 3. A matching-base log would give the same equation."],[String.raw`x=\frac{1+\ln5/\ln3}{2}`,"Add 1, then divide the whole result by 2. Keep this exact form."],[String.raw`x\approx1.232487`,"Round only at the end, then substitute into the original equation."]]},
 {tex:String.raw`2e^{12x}=17`,steps:[[String.raw`e^{12x}=\frac{17}{2}`,"Divide by 2 before taking a logarithm."],[String.raw`12x=\ln\frac{17}{2}`,"Natural logarithm undoes the base-e exponential."],[String.raw`x=\frac{\ln(17/2)}{12}\approx0.178339`,"Divide by 12. The logarithm applies to the entire positive quotient."]]},
 {tex:String.raw`10(1.234^t-13)=50`,steps:[[String.raw`1.234^t-13=5\quad\Longrightarrow\quad1.234^t=18`,"Undo the outside multiplication, then undo the subtraction."],[String.raw`t\ln1.234=\ln18`,"Take logarithms only after isolating the exponential."],[String.raw`t=\frac{\ln18}{\ln1.234}\approx13.746595`,"Divide by the logarithm of the base."]]},
 {tex:String.raw`x^2 10^x-x10^x=2(10^x)`,steps:[[String.raw`10^x(x^2-x-2)=0`,"Move all terms to one side and factor out the common exponential."],[String.raw`10^x(x-2)(x+1)=0`,"Factor the quadratic."],[String.raw`10^x>0\quad\text{for every real }x`,"The exponential factor can never equal zero."],[String.raw`x=2\quad\text{or}\quad x=-1`,"Only the polynomial factors contribute solutions."]]},
 {tex:String.raw`\frac{12}{1+e^{-x}}=3`,steps:[[String.raw`12=3(1+e^{-x})`,"The denominator is positive, so multiplication is valid."],[String.raw`4=1+e^{-x}\quad\Longrightarrow\quad e^{-x}=3`,"Divide by 3, then subtract 1."],[String.raw`-x=\ln3\quad\Longrightarrow\quad x=-\ln3`,"Keep the minus sign on the exponent. The negative solution makes the denominator 4."]]},
 {tex:String.raw`3(0.75)^{2x}-2=5`,steps:[[String.raw`(0.75)^{2x}=\frac73`,"Add 2, then divide by 3. The exponential is now isolated."],[String.raw`2x\ln(0.75)=\ln(7/3)`,"Taking a logarithm works for a base between zero and one too."],[String.raw`x=\frac{\ln(7/3)}{2\ln(0.75)}`,"The denominator is negative and the numerator positive, so x is negative."]]},
];
const mixedCases=[
 {tex:String.raw`7^{2x-1}=3^{5x}`,steps:[[String.raw`(2x-1)\ln7=5x\ln3`,"Apply ln to both sides. Bring down each entire exponent."],[String.raw`2x\ln7-\ln7=5x\ln3`,"Distribute ln 7 across 2x − 1."],[String.raw`x(2\ln7-5\ln3)=\ln7`,"Collect all terms containing x and factor x out."],[String.raw`x=\frac{\ln7}{2\ln7-5\ln3}`,"Divide by the coefficient of x. It is negative, so x is negative."]]},
 {tex:String.raw`4^x=5^{3x-1}`,steps:[[String.raw`x\ln4=(3x-1)\ln5`,"Take logarithms of both sides."],[String.raw`x\ln4=3x\ln5-\ln5`,"Distribute across the entire exponent."],[String.raw`x(\ln4-3\ln5)=-\ln5`,"Collect the x terms."],[String.raw`x=\frac{\ln5}{3\ln5-\ln4}`,"Multiplying numerator and denominator by −1 gives this positive form."]]},
 {tex:String.raw`7^{2x+11}=3^{4x}`,steps:[[String.raw`(2x+11)\ln7=4x\ln3`,"Bring both variable exponents down."],[String.raw`2x\ln7+11\ln7=4x\ln3`,"Distribute without losing the 11."],[String.raw`11\ln7=x(4\ln3-2\ln7)`,"Keep the constant on one side and factor x on the other."],[String.raw`x=\frac{11\ln7}{4\ln3-2\ln7}`,"The denominator is positive. The solution can be large even when the bases are small."]]},
];
const quadraticCases=[
 {tex:String.raw`3^{2x}-3^x-6=0`,steps:[[String.raw`u=3^x>0,\quad3^{2x}=(3^x)^2=u^2`,"Replace the repeated exponential by a positive new variable."],[String.raw`u^2-u-6=0\quad\Longrightarrow\quad(u-3)(u+2)=0`,"Solve the quadratic in u."],[String.raw`u=3\quad\text{or}\quad u=-2`,"The negative root cannot be an exponential output."],[String.raw`3^x=3\quad\Longrightarrow\quad x=1`,"Return to the original variable. The solution is x = 1, not u = 3."]]},
 {tex:String.raw`7e^{2x}+137e^x-60=0`,steps:[[String.raw`u=e^x>0\quad\Longrightarrow\quad7u^2+137u-60=0`,"Write e²ˣ as (eˣ)² before substituting."],[String.raw`(7u-3)(u+20)=0`,"Factor the quadratic."],[String.raw`u=\frac37\quad\text{or}\quad u=-20`,"Only u = 3/7 is positive."],[String.raw`e^x=\frac37\quad\Longrightarrow\quad x=\ln\frac37`,"The accepted exponential output is less than 1, so x is negative."]]},
];
const logarithmCases=[
 {tex:String.raw`\log_2(3x-1)=\log_2(-2-x)`,domain:String.raw`x>\frac13\ \text{and}\ x<-2`,presets:[-0.25,0,1],inputs:x=>[3*x-1,-2-x],sides:x=>[Math.log2(3*x-1),Math.log2(-2-x)],steps:[[String.raw`3x-1>0,\quad-2-x>0`,"Check each original input first. Their allowed intervals do not overlap."],[String.raw`3x-1=-2-x\quad\Longrightarrow\quad x=-\frac14`,"Equating inputs produces an algebraic candidate."],[String.raw`3(-\tfrac14)-1=-\frac74,\quad-2+\frac14=-\frac74`,"Both original log inputs are negative. Matching negative inputs does not make real logarithms exist."],[String.raw`\boxed{\text{No real solution}}`,"Reject the candidate. In fact, the original equation has no real domain."]]},
 {tex:String.raw`\log(1-7x)=\log(x^2+11)`,domain:String.raw`x<\frac17`,presets:[-5,-2,0],inputs:x=>[1-7*x,x*x+11],sides:x=>[Math.log10(1-7*x),Math.log10(x*x+11)],steps:[[String.raw`1-7x>0\quad\Longrightarrow\quad x<\frac17`,"The other input x² + 11 is positive for all real x."],[String.raw`1-7x=x^2+11\quad\Longrightarrow\quad x^2+7x+10=0`,"The same logarithm base is one-to-one on positive inputs."],[String.raw`(x+5)(x+2)=0\quad\Longrightarrow\quad x=-5,-2`,"Factor to get two candidates."],[String.raw`\boxed{x=-5\ \text{or}\ x=-2}`,"Both candidates are allowed. Negative x values can produce positive log inputs."]]},
 {tex:String.raw`\ln(2x-3)+1=0`,domain:String.raw`x>\frac32`,presets:[1.5,(3+Math.exp(-1))/2,2],inputs:x=>[2*x-3],sides:x=>[Math.log(2*x-3)+1,0],steps:[[String.raw`2x-3>0\quad\Longrightarrow\quad x>\frac32`,"Record the original domain."],[String.raw`\ln(2x-3)=-1\quad\Longrightarrow\quad2x-3=e^{-1}`,"Isolate the log, then exponentiate with base e."],[String.raw`x=\frac{3+e^{-1}}2`,"Undo the linear expression."],[String.raw`\boxed{x=\frac{3+e^{-1}}2\approx1.683940}`,"Its log input is e⁻¹ > 0, so the solution is valid."]]},
 {tex:String.raw`\log_3(x+15)-\log_3(x-1)=2`,domain:String.raw`x>1`,presets:[1,3,0],inputs:x=>[x+15,x-1],sides:x=>[(Math.log(x+15)-Math.log(x-1))/Math.log(3),2],steps:[[String.raw`x+15>0,\quad x-1>0\quad\Longrightarrow\quad x>1`,"Intersect the original input restrictions."],[String.raw`\log_3\frac{x+15}{x-1}=2\quad\Longrightarrow\quad\frac{x+15}{x-1}=9`,"Combine the difference before exponentiating."],[String.raw`x+15=9(x-1)\quad\Longrightarrow\quad x=3`,"Clear the denominator and solve."],[String.raw`\boxed{x=3}`,"Both inputs are positive: log₃18 − log₃2 = log₃9 = 2."]]},
 {tex:String.raw`2\log x=\log2+\log(3x-4)`,domain:String.raw`x>\frac43`,presets:[2,4,1],inputs:x=>[x,3*x-4],sides:x=>[2*Math.log10(x),Math.log10(2)+Math.log10(3*x-4)],steps:[[String.raw`x>0,\quad3x-4>0\quad\Longrightarrow\quad x>\frac43`,"Check the individual original inputs, not only their product."],[String.raw`\log(x^2)=\log\big(2(3x-4)\big)`,"Use the power and product laws."],[String.raw`x^2=6x-8\quad\Longrightarrow\quad(x-2)(x-4)=0`,"Equate positive inputs and factor."],[String.raw`\boxed{x=2\ \text{or}\ x=4}`,"Both candidates pass the original domain and equality checks."]]},
 {tex:String.raw`\ln(x-2)+\ln3=\ln(5x-7)`,domain:String.raw`x>2`,presets:[0.5,2,3],inputs:x=>[x-2,5*x-7],sides:x=>[Math.log(x-2)+Math.log(3),Math.log(5*x-7)],steps:[[String.raw`x-2>0,\quad5x-7>0\quad\Longrightarrow\quad x>2`,"Intersect the original logarithm domains."],[String.raw`\ln\big(3(x-2)\big)=\ln(5x-7)`,"Combine the sum into one logarithm."],[String.raw`3(x-2)=5x-7\quad\Longrightarrow\quad x=\frac12`,"Solve the equation of inputs."],[String.raw`\boxed{\text{No real solution}}`,"The candidate x = 1/2 makes both variable log inputs negative. Reject it."]]},
 {tex:String.raw`\log_{1/2}(2+x^2)=-6`,domain:String.raw`x\in\mathbb{R}`,presets:[-Math.sqrt(62),Math.sqrt(62),0],inputs:x=>[2+x*x],sides:x=>[Math.log(2+x*x)/Math.log(.5),-6],steps:[[String.raw`2+x^2>0\quad\text{for all real }x`,"The original input is always positive. The base 1/2 is valid."],[String.raw`2+x^2=(1/2)^{-6}=64`,"Rewrite the logarithmic equation in exponential form."],[String.raw`x^2=62\quad\Longrightarrow\quad x=\pm\sqrt{62}`,"Keep both square roots."],[String.raw`\boxed{x=-\sqrt{62}\ \text{or}\ x=\sqrt{62}}`,"Both solutions produce the positive input 64, and log base 1/2 of 64 is −6."]]},
];
const checks=[
 ["Same base",String.raw`5^{x-1}=125`,['3','4','5'],1,"Rewrite 125 = 5³, then solve x − 1 = 3."],
 ["Both square roots",String.raw`10^{2x^2-3}=10^{9-x^2}`,['2',String.raw`\{-2,2\}`,'4'],1,"The exponents give 3x² = 12. Both −2 and 2 work."],
 ["Isolate first",String.raw`2e^{12x}=17`,[String.raw`\frac{\ln(17/2)}{12}`,String.raw`\frac{\ln17}{24}`,String.raw`\ln(17/24)`],0,"Divide by 2 first, then take ln and divide by 12."],
 ["Two different bases",String.raw`4^x=5^{3x-1}`,[String.raw`\frac{\ln5}{\ln4}`,String.raw`\frac{\ln5}{3\ln5-\ln4}`,String.raw`\frac1{3-1}`],1,"Taking ln puts x on both sides. Collect and factor x before dividing."],
 ["Return from substitution",String.raw`3^{2x}-3^x-6=0`,['3','-2','1'],2,"u = 3ˣ gives u = 3 or −2. Reject −2 and solve 3ˣ = 3, giving x = 1."],
 ["Positive exponential output",String.raw`7e^{2x}+137e^x-60=0`,[String.raw`\ln(3/7)`,String.raw`\{-20,3/7\}`,String.raw`\ln20`],0,"The quadratic in u = eˣ gives 3/7 and −20. Only the positive root can equal eˣ."],
 ["Keep the negative sign",String.raw`\frac{12}{1+e^{-x}}=3`,[String.raw`\ln3`,String.raw`-\ln3`,String.raw`\ln4`],1,"Isolating gives e⁻ˣ = 3, so −x = ln 3."],
 ["No shared domain",String.raw`\log_2(3x-1)=\log_2(-2-x)`,[String.raw`-\frac14`,String.raw`\text{No real solution}`,'0'],1,"The first input requires x > 1/3, while the second requires x < −2. No x satisfies both."],
 ["Negative x can be legal",String.raw`\log(1-7x)=\log(x^2+11)`,[String.raw`\{-5,-2\}`,String.raw`\text{No real solution}`,'-2'],0,"Both −5 and −2 make the original log inputs positive and equal."],
 ["Combine then check",String.raw`\log_3(x+15)-\log_3(x-1)=2`,['1','3','9'],1,"The quotient equals 3² = 9. Solving gives x = 3, which lies in x > 1."],
 ["Reject an extraneous candidate",String.raw`\ln(x-2)+\ln3=\ln(5x-7)`,[String.raw`\frac12`,String.raw`\text{No real solution}`,'3'],1,"The algebraic candidate 1/2 violates the original restriction x > 2."],
 ["Continuous doubling time",String.raw`2P=Pe^{0.045t}`,[String.raw`\frac{\ln2}{0.045}`,String.raw`\frac2{0.045}`,String.raw`\ln(2/0.045)`],0,"Cancel P, isolate e^(0.045t) = 2, then take ln. Time is in years."],
];

const workshop=(id,title,cases)=>`<div class="laws-lab laws-lab--dropdown" data-reveal><div class="laws-controls"><p class="tool-label">${title}</p>${choices(id+'-case','Choose an equation',cases.map(c=>c.tex))}${stepUI(id)}</div><div class="laws-result" id="${id}-step" aria-live="polite"></div></div>`;
document.querySelector('#app').innerHTML=`${renderLessonHeader('4.5')}<main class="laws-lesson equations-lesson">
<section class="lesson-hero lesson-hero--equations"><div class="lesson-hero__copy" data-reveal><p class="lesson-kicker"><span>Section 4.5</span> Exponential & logarithmic equations</p><h1>Undo the operation.<br><em>Check the answer.</em></h1><p class="lesson-hero__lede">Find the unknown exponent, recover a logarithm's input, or solve for elapsed time. Choose the right algebraic move—and keep only answers the original equation allows.</p><div class="lesson-hero__actions"><a class="lesson-button lesson-button--dark" href="#choose-method">Choose your method</a><span>About 50 minutes · interactive</span></div></div><div class="equation-hero-art" data-reveal><p class="tool-label">Inverse operations unlock the exponent</p><div class="laws-equation">${M(String.raw`e^{\textcolor{#c5442d}{x}}=\textcolor{#246240}{5}`)}</div><span class="equation-hero-arrow">↓ take ln</span><div class="laws-equation">${M(String.raw`\textcolor{#c5442d}{x}=\ln\textcolor{#246240}{5}`)}</div><p>First isolate. Then undo.<br>Finally, check the original equation.</p></div></section>
<section class="lesson-objectives" aria-label="Lesson objectives" data-reveal><p>By the end, you can</p><ol><li><span>01</span><p>Choose a solving strategy from the equation</p></li><li><span>02</span><p>Use logarithms and exponential substitutions</p></li><li><span>03</span><p>Test candidates in the original log domains</p></li><li><span>04</span><p>Solve growth, decay, and cooling models</p></li></ol></section>
<section class="lesson-section" id="choose-method">${intro('01','Recognize the structure','Where is<br>the unknown?',`An exponential equation has the variable <strong>in an exponent</strong>. A logarithmic equation has the variable <strong>inside a logarithm input</strong>. A constant log or a constant power does not determine the equation type.`)}<div class="laws-lab laws-lab--dropdown" data-reveal><div class="laws-controls"><p class="tool-label">Equation classifier</p>${choices('classify-case','Inspect an equation',classification.map(c=>c[0]))}<label for="classify-answer">Equation type</label><select id="classify-answer"><option value="">Choose a type</option><option value="exponential">Exponential</option><option value="logarithmic">Logarithmic</option><option value="neither">Neither</option></select><button type="button" class="laws-button" id="classify-check">Check the type</button><p class="answer-feedback" id="classify-feedback" aria-live="polite"></p></div><div class="laws-result"><p class="tool-label">Strategy map</p><ol class="equation-method-list"><li><strong>Same exponential base?</strong><p>Rewrite and equate the exponents.</p></li><li><strong>An isolated exponential?</strong><p>Take a logarithm of both sides.</p></li><li><strong>A repeated exponential?</strong><p>Factor or substitute a positive new variable.</p></li><li><strong>Unknown inside a log?</strong><p>Record the domain, combine or isolate, undo, then check.</p></li></ol></div></div></section>
<section class="lesson-section lesson-section--soft" id="exponentials">${intro('02','Solve exponentials','Isolate the power.<br>Bring down the unknown.',`For ${M(String.raw`a>0,\ a\ne1`)}, ${M(String.raw`a^u=a^v\Longrightarrow u=v`)}. If the bases do not match neatly, use ${M(String.raw`\ln(a^u)=u\ln a`)}. Exponential outputs are always positive.`)}${workshop('exp','Exponential solving workshop',exponentialCases)}</section>
<section class="lesson-section" id="intersection">${intro('03','Explore an equation','Move the target.<br>Find the crossing.',`A solution to ${M(String.raw`Ab^{kx+h}+c=R`)} is an intersection of the exponential curve with the horizontal target line. Here ${M('A>0')} and ${M('k>0')}. If ${M(String.raw`R\le c`)}, there is no real solution.`)}<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Target and curve explorer</p><label for="solve-base">Base b</label><select id="solve-base"><option value="2">2</option><option value="e">e</option><option value="0.5">½</option></select>${range('solve-a','Multiplier A',1,4,1,2)}${range('solve-k','Exponent coefficient k',1,3,1,1)}${range('solve-h','Exponent shift h',-3,3,0.5,0)}${range('solve-c','Outside shift c',-3,3,0.5,1)}<label for="solve-target">Target R</label><input type="number" id="solve-target" step="any" value="5"><div class="laws-note" id="solve-reading" aria-live="polite"></div></div><div class="equation-plot"><svg id="solve-chart" viewBox="0 0 660 440" role="img" aria-label="Exponential curve and a horizontal target line"></svg><p>Coral: exponential · violet: target · gold: solution. Horizontal axis: x. Vertical axis: output. The window shows −5 ≤ x ≤ 5; some solutions lie beyond it.</p></div></div></section>
<section class="lesson-section lesson-section--soft" id="two-bases">${intro('04','Unknown on both sides','Different bases?<br>Collect the x terms.',`Taking logarithms works even when both sides have variable exponents. Distribute carefully, collect all terms containing ${M('x')}, then factor ${M('x')} before dividing.`)}${workshop('mixed','Two-base equation workshop',mixedCases)}</section>
<section class="lesson-section" id="substitution">${intro('05','A quadratic in disguise','Give the power a name.<br>Then return to x.',`${M(String.raw`a^{2x}=(a^x)^2`)} suggests ${M(String.raw`u=a^x>0`)}. Solve the quadratic in ${M('u')}, reject nonpositive values, then solve for ${M('x')}. A negative exponential output is impossible; a negative exponent is allowed.`)}${workshop('quad','Positive-substitution workshop',quadraticCases)}</section>
<section class="lesson-section lesson-section--soft" id="logarithms">${intro('06','Solve and validate','A candidate<br>must pass two tests.',`Write every original log input as a strict positive inequality. After solving, check <strong>both</strong> the original domain and the original equality. Combining logarithms does not remove the individual input restrictions.`)}${workshop('log','Logarithmic equation workshop',logarithmCases)}<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Candidate gate</p><p>Test values in the equation selected above.</p><label for="candidate-x">Candidate x</label><input type="number" id="candidate-x" step="any" value="-0.25"><div class="equation-candidates" id="candidate-presets"></div><div class="laws-note" id="candidate-domain" aria-live="polite"></div></div><div class="laws-result" id="candidate-reading" aria-live="polite"></div></div></section>
<section class="lesson-section" id="models">${intro('07','Time in a model','Solve for time.<br>Keep the units.',`Divide by the initial amount, isolate the exponential, then take a logarithm. A time should fit its context. For continuous growth use ${M(String.raw`A=Pe^{rt}`)}; for periodic compounding use ${M(String.raw`A=P(1+r/n)^{nt}`)}.`)}<div class="laws-lab" data-reveal><div class="laws-controls"><p class="tool-label">Time-model laboratory</p><label for="model-kind-45">Choose a model</label><select id="model-kind-45"><option value="decay">Radioactive mass · days</option><option value="continuous">Continuous savings · years</option><option value="periodic">Semiannual savings · years</option><option value="cooling">Engine cooling · minutes</option></select><div id="time-controls"></div><p id="time-context"></p></div><div class="laws-result"><div id="time-reading" aria-live="polite"></div><svg id="time-chart" viewBox="0 0 660 400" role="img" aria-label="Model value over time with the target crossing marked"></svg><p class="laws-caption" id="time-axis-label"></p></div></div><aside class="laws-note">For a doubling equation, the principal cancels: ${M(String.raw`2P=Pe^{rt}\Longrightarrow t=\frac{\ln2}{r}`)}. A stated percentage rate must be written as a decimal.</aside></section>
<section class="lesson-section lesson-section--ink" id="readiness">${intro('08','Practice','Choose. Solve.<br>Check.',"Give an exact answer when possible. Use the explanation to identify the step that decides whether a candidate survives.")}<p class="laws-score" id="equation-score" aria-live="polite">0 of ${checks.length} checks solved</p><div class="laws-check-grid">${checks.map((q,i)=>`<article class="laws-check"><p class="tool-label">${q[0]}</p><h3>${M(q[1])}</h3>${renderMathDropdown(`eq-practice-${i}`,"Your answer",q[2],M,{placeholder:"Select an answer"})}<button type="button" class="laws-button" data-eq-check="${i}">Check answer</button><p class="answer-feedback" id="eq-feedback-${i}" aria-live="polite"></p></article>`).join('')}</div></section>
</main>${renderLessonFooter({previous:{href:'pages/sections/4-4.html',label:'Section 4.4 · Laws of logarithms'},next:{href:"pages/sections/6-1.html",label:"Section 6.1 · Angle measure"}})}`;

function stepper(id,cases){initMathDropdown(id+"-case",cases.map(c=>c.tex),M);let index=0;const render=()=>{const c=cases[selected(id+'-case')],s=c.steps[index];$(id+'-step').innerHTML=`<p class="tool-label">Move ${index+1}</p><div class="laws-equation">${M(s[0])}</div><p>${s[1]}</p>`;$(id+'-back').disabled=index===0;$(id+'-next').disabled=index===c.steps.length-1;$(id+'-progress').textContent=`Step ${index+1} of ${c.steps.length}`;};$(id+'-back').addEventListener('click',()=>{if(index>0)index--;render();});$(id+'-next').addEventListener('click',()=>{if(index<cases[selected(id+'-case')].steps.length-1)index++;render();});$(id+'-case').addEventListener('change',()=>{index=0;render();});render();}
[['exp',exponentialCases],['mixed',mixedCases],['quad',quadraticCases],['log',logarithmCases]].forEach(([id,cases])=>stepper(id,cases));
initMathDropdown('classify-case',classification.map(c=>c[0]),M);
$('classify-check').addEventListener('click',()=>{const c=classification[selected('classify-case')],answer=$('classify-answer').value;if(!answer){setFeedback($('classify-feedback'),false,'Choose an equation type first.');return;}setFeedback($('classify-feedback'),answer===c[1],(answer===c[1]?'Correct. ':'Try again. ')+c[2]);});
$('classify-case').addEventListener('change',()=>{$('classify-answer').value='';$('classify-feedback').textContent='';$('classify-feedback').classList.remove('is-correct','is-incorrect');});

function plot(svg,xmin,xmax,ymin,ymax,width=660,height=440){
 const l=56,r=24,t=22,b=44,X=x=>l+(x-xmin)*(width-l-r)/(xmax-xmin),Y=y=>height-b-(y-ymin)*(height-t-b)/(ymax-ymin),clip=svg.id+'-clip';let grid='';
 for(let i=0;i<=5;i++){const x=xmin+(xmax-xmin)*i/5,y=ymin+(ymax-ymin)*i/5;grid+=`<line class="eq-grid" x1="${X(x)}" x2="${X(x)}" y1="${t}" y2="${height-b}"/><line class="eq-grid" x1="${l}" x2="${width-r}" y1="${Y(y)}" y2="${Y(y)}"/><text class="eq-tick" x="${X(x)}" y="${height-16}" text-anchor="middle">${fmt(x,1)}</text><text class="eq-tick" x="${l-9}" y="${Y(y)+4}" text-anchor="end">${fmt(y,1)}</text>`;}
 svg.innerHTML=`<defs><clipPath id="${clip}"><rect x="${l}" y="${t}" width="${width-l-r}" height="${height-t-b}"/></clipPath></defs>${grid}`;
 const add=content=>svg.insertAdjacentHTML('beforeend',`<g clip-path="url(#${clip})">${content}</g>`),line=(y,color)=>`<line stroke="${color}" stroke-width="2" stroke-dasharray="7 5" x1="${l}" x2="${width-r}" y1="${Y(y)}" y2="${Y(y)}"/>`,dot=(x,y)=>`<circle cx="${X(x)}" cy="${Y(y)}" r="6" fill="var(--gold)" stroke="var(--ink)" stroke-width="2"/>`;
 const curve=fn=>{let d='';for(let i=0;i<=700;i++){const x=xmin+(xmax-xmin)*i/700,y=fn(x),bounded=Math.max(ymin-(ymax-ymin),Math.min(ymax+(ymax-ymin),y));if(Number.isFinite(bounded))d+=`${d?'L':'M'}${X(x).toFixed(2)},${Y(bounded).toFixed(2)} `;}return `<path d="${d}" fill="none" stroke="var(--coral)" stroke-width="4"/>`;};
 add(`${ymin<=0&&ymax>=0?line(0,'var(--ink)'):''}${xmin<=0&&xmax>=0?`<line stroke="var(--ink)" x1="${X(0)}" x2="${X(0)}" y1="${t}" y2="${height-b}"/>`:''}`);return{X,Y,add,line,dot,curve};
}
function renderSolve(){
 const b=$('solve-base').value==='e'?Math.E:Number($('solve-base').value),name=$('solve-base').value,A=Number($('solve-a').value),k=Number($('solve-k').value),h=Number($('solve-h').value),c=Number($('solve-c').value),R=$('solve-target').valueAsNumber;
 ['a','k','h','c'].forEach(key=>$('solve-'+key+'-value').textContent=fmt({a:A,k,h,c}[key]));
 const finite=Number.isFinite(R),valid=finite&&R>c,x=valid?(Math.log((R-c)/A)/Math.log(b)-h)/k:null;
 const p=plot($('solve-chart'),-5,5,-5,15);p.add(p.curve(x=>A*b**(k*x+h)+c));p.add(p.line(c,'var(--green)'));if(finite&&R>=-5&&R<=15)p.add(p.line(R,'var(--violet)'));if(valid&&x>=-5&&x<=5&&R>=-5&&R<=15)p.add(p.dot(x,R));
 $('solve-reading').innerHTML=`<p>${M(String.raw`${A}(${name})^{${k}x${h<0?'': '+'}${h}}${c<0?'':'+'}${c}= ${finite?R:'R'}`)}</p>${!finite?'<strong>Enter a finite target.</strong>':!valid?`<strong>No real solution.</strong><p>The isolated exponential would be ${M(String.raw`\frac{${R}-(${c})}{${A}}\le0`)}. A positive exponential cannot equal zero or a negative number.</p>`:`<strong>Solution: ${M(String.raw`x\approx${x.toFixed(6)}`)}</strong><p>${M(String.raw`x=\frac{\ln((R-c)/A)/\ln b-h}{k}`)}</p><p>${x<-5||x>5||R<-5||R>15?'The crossing is outside the displayed graph window.':'The gold crossing satisfies the equation.'} The green dashed line is the horizontal asymptote.</p>`}`;
}
['solve-base','solve-a','solve-k','solve-h','solve-c','solve-target'].forEach(id=>$(id).addEventListener($(id).tagName==='SELECT'?'change':'input',renderSolve));renderSolve();
function candidatePresets(){const c=logarithmCases[selected('log-case')];$('candidate-x').value=c.presets[0];$('candidate-presets').innerHTML=c.presets.map(x=>`<button type="button" class="laws-button" data-candidate="${x}">Try ${fmt(x,6)}</button>`).join('');$('candidate-presets').querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>{$('candidate-x').value=btn.dataset.candidate;renderCandidate();}));renderCandidate();}
function renderCandidate(){const c=logarithmCases[selected('log-case')],x=$('candidate-x').valueAsNumber; $('candidate-domain').innerHTML=`<strong>Original restrictions</strong><p>${M(c.domain)}</p>`;if(!Number.isFinite(x)){$('candidate-reading').innerHTML='<p>Enter a finite candidate.</p>';return;}const inputs=c.inputs(x),domain=inputs.every(v=>v>0);if(!domain){$('candidate-reading').innerHTML=`<p class="tool-label">Domain test</p>${inputs.map((v,i)=>`<p class="${v>0?'eq-pass':'eq-fail'}">Input ${i+1}: ${fmt(v)} ${v>0?'✓ positive':'× not positive'}</p>`).join('')}<div class="laws-note laws-note--coral"><strong>Rejected: an original logarithm is undefined.</strong><p>Do not evaluate real logarithms of zero or negative numbers.</p></div>`;return;}const [left,right]=c.sides(x),gap=Math.abs(left-right),equal=gap<=1e-7*Math.max(1,Math.abs(left),Math.abs(right));$('candidate-reading').innerHTML=`<p class="tool-label">Domain passed · now check equality</p>${inputs.map((v,i)=>`<p class="eq-pass">Input ${i+1}: ${fmt(v)} ✓ positive</p>`).join('')}<div class="laws-number-tiles"><div><span>Original left side</span><strong>${fmt(left,6)}</strong></div><div><span>Original right side</span><strong>${fmt(right,6)}</strong></div></div><div class="laws-note ${equal?'':'laws-note--coral'}"><strong>${equal?'Accepted: it satisfies the original equation.':'Allowed input, but not a solution.'}</strong><p>${equal?'Both domain and equality checks pass.':'Positive log inputs alone are not enough. The two sides must also agree.'} Decimal equality is checked within a small numerical tolerance.</p></div>`;}
$('log-case').addEventListener('change',candidatePresets);$('candidate-x').addEventListener('input',renderCandidate);candidatePresets();
const modelConfigs={
 decay:{fields:[['target','Target mass (mg)',50,300,10,200]],context:`A 300-mg radioactive sample follows ${M(String.raw`m(t)=300e^{-0.00495t}`)}. Time is measured in days.`},
 continuous:{fields:[['rate','Annual rate (%)',1,10,0.25,4.5],['target','Target multiple of principal',1,4,0.25,2]],context:`Continuous compounding: ${M(String.raw`A=Pe^{rt}`)}. The initial principal cancels when the target is expressed as a multiple.`},
 periodic:{fields:[['rate','Annual rate (%)',1,12,0.25,8.5],['target','Target balance ($)',5000,10000,250,7000]],context:'Start with $5,000 and compound twice per year. Time is in years; n = 2, and the annual rate is a decimal.'},
 cooling:{fields:[['target','Target temperature (°F)',25,220,5,100]],context:`A 220°F engine cools toward 20°F ambient air: ${M(String.raw`\ln((T-20)/200)=-0.11t`)}. Time is in minutes.`},
};
function configureTime(){const cfg=modelConfigs[$('model-kind-45').value];$('time-controls').innerHTML=cfg.fields.map(([key,label,min,max,step,value])=>range('time-'+key,label,min,max,step,value)).join('');$('time-context').innerHTML=cfg.context;cfg.fields.forEach(([key])=>$('time-'+key).addEventListener('input',renderTime));renderTime();}
function renderTime(){const kind=$('model-kind-45').value,cfg=modelConfigs[kind],values={};cfg.fields.forEach(([key])=>{values[key]=Number($('time-'+key).value);$('time-'+key+'-value').textContent=fmt(values[key]);});const target=values.target,r=values.rate/100;let time,fn,formula,work,unit,top,isolated,note='';
 if(kind==='decay'){time=Math.log(target/300)/-.00495;fn=t=>300*Math.exp(-.00495*t);formula=String.raw`m(t)=300e^{-0.00495t}`;work=String.raw`t=\frac{\ln(${target}/300)}{-0.00495}`;unit='days';top=330;isolated=String.raw`e^{-0.00495t}=\frac{${target}}{300}`;}
 else if(kind==='continuous'){time=Math.log(target)/r;fn=t=>Math.exp(r*t);formula=String.raw`\frac{A(t)}P=e^{${r}t}`;work=String.raw`t=\frac{\ln(${target})}{${r}}`;unit='years';top=target*1.3;isolated=String.raw`e^{${r}t}=${target}`;}
 else if(kind==='periodic'){time=Math.log(target/5000)/(2*Math.log1p(r/2));fn=t=>5000*(1+r/2)**(2*t);formula=String.raw`A(t)=5000(1+${r}/2)^{2t}`;work=String.raw`t=\frac{\ln(${target}/5000)}{2\ln(1+${r}/2)}`;unit='years';top=target*1.3;isolated=String.raw`(1+${r}/2)^{2t}=\frac{${target}}{5000}`;}
 else{time=Math.log((target-20)/200)/-.11;fn=t=>20+200*Math.exp(-.11*t);formula=String.raw`T(t)=20+200e^{-0.11t}`;work=String.raw`t=\frac{\ln((${target}-20)/200)}{-0.11}`;unit='minutes';top=240;isolated=String.raw`e^{-0.11t}=\frac{${target}-20}{200}`;note=`<p>At 20 minutes, ${M(String.raw`T(20)=20+200e^{-2.2}\approx42.16^\circ\!F`)}. Temperature approaches 20°F from above.</p>`;}
 $('time-axis-label').textContent=`Horizontal axis: time in ${unit}. Vertical axis: ${kind==='decay'?'mass in mg':kind==='continuous'?'multiple of principal':kind==='periodic'?'balance in dollars':'temperature in °F'}. Violet line: target; gold point: crossing.`;const horizon=Math.max(kind==='decay'?100:kind==='cooling'?30:5,time*1.25);$('time-reading').innerHTML=`<p class="tool-label">Isolate · take ln · solve</p><div class="laws-equation">${M(formula)}</div><div class="eq-time-value"><strong>${fmt(time,3)}</strong><span>${unit} to reach the target</span></div><p>Isolate the exponential: ${M(isolated)}</p><div class="laws-equation">${M(work)}</div><p>At this time, the model gives approximately ${fmt(fn(time),3)}, matching the target ${target}. ${time===0?'The target equals the starting value, so the time is zero.':''}</p>${note}`;const p=plot($('time-chart'),0,horizon,0,top,660,400);p.add(p.curve(fn)+p.line(target,'var(--violet)')+p.dot(time,target));if(kind==='cooling')p.add(p.line(20,'var(--green)'));}
$('model-kind-45').addEventListener('change',configureTime);configureTime();
checks.forEach((q,i)=>initMathDropdown(`eq-practice-${i}`,q[2],M));
const solved=new Set();document.querySelectorAll('[data-eq-check]').forEach(btn=>btn.addEventListener('click',()=>{const i=Number(btn.dataset.eqCheck),choice=$("eq-practice-"+i).dataset.value;if(choice===""){setFeedback($('eq-feedback-'+i),false,'Choose an answer first.');return;}const correct=Number(choice)===checks[i][3];if(correct)solved.add(i);setFeedback($('eq-feedback-'+i),correct,(correct?'Correct. ':'Try again. ')+checks[i][4]);$('equation-score').textContent=`${solved.size} of ${checks.length} checks solved${solved.size===checks.length?' · Ready to move on!':''}`;}));
initLessonChrome();
